---
title: "St. Louis Lead Inequity"
format: html
---
Read in & explore data
```{r}
#| message: false
# attach packages
library(tidyverse)
library(janitor)
```

```{r}
#| message: false
# read in data
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"),)

stl_lead <- stl_lead %>%
  janitor::clean_names()

# data exploration
names(stl_lead)

dim(stl_lead)

skimr::skim(stl_lead)
```

Create data frame
```{r}
# add column prop_white and create data frame
stl_lead_prop <- data.frame(stl_lead) %>% 
  dplyr::mutate(prop_white = (white / total_pop) * 100) 

# check new dimensions 
dim(stl_lead_prop)
```

Visualize data 
```{r}
# scatterplot
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point(alpha = 0.5, colour = "red") + 
  labs(x = "Percent Elevated", y = "Proportion White")

stl_lead_plot

# save figure
ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```
Census tracts with higher percentages of white children tend to have lower percent elevated blood lead levels.

```{r}
# histogram
stl_lead_histogram <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram() +
  labs(x = "Percent elevated")

stl_lead_histogram

ggsave(here::here("figs", "stl_lead_histogram.jpg"), height = 6, width = 5)
```

